export const PRELOADED_MONTHLY_WORKERS = [
  {
    "employeeId": "CT21120020",
    "name": "강경현",
    "part": "CDA 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT14040010",
    "name": "강도원",
    "part": "FD",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT18120030",
    "name": "강지은",
    "part": "CDB 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT23040030",
    "name": "고민조",
    "part": "CDA 2",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 123,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 184.5,
    "overtimeDayCount": 1,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "2시간 3분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 180,
    "leaveGrantLabel": "3시간 0분"
  },
  {
    "employeeId": "CT25100020",
    "name": "고소연",
    "part": "digital marketing design",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT25010010",
    "name": "고은아",
    "part": "CDA 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT21120010",
    "name": "고은혜",
    "part": "CDA 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 286,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 429,
    "overtimeDayCount": 2,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "4시간 46분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 420,
    "leaveGrantLabel": "7시간 0분"
  },
  {
    "employeeId": "CT23100060",
    "name": "곽수빈",
    "part": "Management Support",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 580,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 870,
    "overtimeDayCount": 3,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "9시간 40분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 870,
    "leaveGrantLabel": "14시간 30분"
  },
  {
    "employeeId": "CT17030010",
    "name": "곽지수",
    "part": "FD 2",
    "div": "",
    "rank": "",
    "nightMinutes": 95,
    "overtimeMinutes": 829,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 1291,
    "overtimeDayCount": 4,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "1시간 35분",
    "overtimeLabel": "13시간 49분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 1290,
    "leaveGrantLabel": "21시간 30분"
  },
  {
    "employeeId": "CT26020010",
    "name": "김가영",
    "part": "UXUI 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 189,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 283.5,
    "overtimeDayCount": 2,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "3시간 9분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 270,
    "leaveGrantLabel": "4시간 30분"
  },
  {
    "employeeId": "CT21050020",
    "name": "김가윤",
    "part": "FD 2",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT19030010",
    "name": "김동현",
    "part": "digital marketing 3",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 165,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 247.5,
    "overtimeDayCount": 1,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "2시간 45분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 240,
    "leaveGrantLabel": "4시간 0분"
  },
  {
    "employeeId": "CT25020040",
    "name": "김명선",
    "part": "PLN 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 528,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 792,
    "overtimeDayCount": 6,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "8시간 48분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 780,
    "leaveGrantLabel": "13시간 0분"
  },
  {
    "employeeId": "CT15040010",
    "name": "김미정",
    "part": "CDA 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 187,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 280.5,
    "overtimeDayCount": 1,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "3시간 7분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 270,
    "leaveGrantLabel": "4시간 30분"
  },
  {
    "employeeId": "CT16050020",
    "name": "김민영",
    "part": "CDA 3",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT24090030",
    "name": "김서은",
    "part": "digital marketing 2",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT25100010",
    "name": "김선아",
    "part": "FD 4",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT24030040",
    "name": "김소현",
    "part": "CDC 3",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 496,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 744,
    "overtimeDayCount": 4,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "8시간 16분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 720,
    "leaveGrantLabel": "12시간 0분"
  },
  {
    "employeeId": "CT23050010",
    "name": "김수빈",
    "part": "digital marketing 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 683,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 1024.5,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "11시간 23분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 1020,
    "leaveGrantLabel": "17시간 0분"
  },
  {
    "employeeId": "CT26020030",
    "name": "김수연",
    "part": "CDC 2",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 140,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 210,
    "overtimeDayCount": 1,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "2시간 20분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 210,
    "leaveGrantLabel": "3시간 30분"
  },
  {
    "employeeId": "CT26010010",
    "name": "김승태",
    "part": "Creative Director",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 13,
    "issueDates": [
      "2026-03-03",
      "2026-03-06",
      "2026-03-11",
      "2026-03-13",
      "2026-03-16",
      "2026-03-18",
      "2026-03-19",
      "2026-03-23",
      "2026-03-24",
      "2026-03-25",
      "2026-03-26",
      "2026-03-27",
      "2026-03-31"
    ],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT24010020",
    "name": "김시우",
    "part": "FD 2",
    "div": "",
    "rank": "",
    "nightMinutes": 81,
    "overtimeMinutes": 359,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 579,
    "overtimeDayCount": 1,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "1시간 21분",
    "overtimeLabel": "5시간 59분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 570,
    "leaveGrantLabel": "9시간 30분"
  },
  {
    "employeeId": "CT22070060",
    "name": "김여정",
    "part": "CDA 2",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 129,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 193.5,
    "overtimeDayCount": 1,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "2시간 9분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 180,
    "leaveGrantLabel": "3시간 0분"
  },
  {
    "employeeId": "CT24040070",
    "name": "김윤지",
    "part": "FD 3",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT25030030",
    "name": "김은정",
    "part": "UXUI 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 95,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 142.5,
    "overtimeDayCount": 1,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "1시간 35분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 120,
    "leaveGrantLabel": "2시간 0분"
  },
  {
    "employeeId": "CT23070020",
    "name": "김은지",
    "part": "UXUI 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT24100010",
    "name": "김은지",
    "part": "CDA 2",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 210,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 315,
    "overtimeDayCount": 2,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "3시간 30분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 300,
    "leaveGrantLabel": "5시간 0분"
  },
  {
    "employeeId": "CT22080020",
    "name": "김은혜",
    "part": "UXUI 2",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 77,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 115.5,
    "overtimeDayCount": 1,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "1시간 17분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 90,
    "leaveGrantLabel": "1시간 30분"
  },
  {
    "employeeId": "CT24010030",
    "name": "김정민",
    "part": "CDB 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT24010070",
    "name": "김정윤",
    "part": "CDB 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 64,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 96,
    "overtimeDayCount": 1,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "1시간 4분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 90,
    "leaveGrantLabel": "1시간 30분"
  },
  {
    "employeeId": "CT21060010",
    "name": "김제인",
    "part": "FD 1",
    "div": "",
    "rank": "",
    "nightMinutes": 97,
    "overtimeMinutes": 710,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 1113.5,
    "overtimeDayCount": 3,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "1시간 37분",
    "overtimeLabel": "11시간 50분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 1110,
    "leaveGrantLabel": "18시간 30분"
  },
  {
    "employeeId": "CT23110030",
    "name": "김조은",
    "part": "CDA 2",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT22030020",
    "name": "김주리",
    "part": "PLN 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 445,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 667.5,
    "overtimeDayCount": 8,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "7시간 25분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 660,
    "leaveGrantLabel": "11시간 0분"
  },
  {
    "employeeId": "CT22110010",
    "name": "김지수",
    "part": "CDA 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 310,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 465,
    "overtimeDayCount": 2,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "5시간 10분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 450,
    "leaveGrantLabel": "7시간 30분"
  },
  {
    "employeeId": "CT24040020",
    "name": "김지연",
    "part": "FD 1",
    "div": "",
    "rank": "",
    "nightMinutes": 130,
    "overtimeMinutes": 1078,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 1682,
    "overtimeDayCount": 3,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "2시간 10분",
    "overtimeLabel": "17시간 58분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 1680,
    "leaveGrantLabel": "28시간 0분"
  },
  {
    "employeeId": "CT23040050",
    "name": "김지원",
    "part": "UXUI 2",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT24090010",
    "name": "김태연",
    "part": "CDA 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT19040010",
    "name": "김현기",
    "part": "PLN",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 142,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 213,
    "overtimeDayCount": 2,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "2시간 22분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 210,
    "leaveGrantLabel": "3시간 30분"
  },
  {
    "employeeId": "CT23090020",
    "name": "김현연",
    "part": "PLN 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT24020020",
    "name": "김현정",
    "part": "CDA 2",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 108,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 162,
    "overtimeDayCount": 1,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "1시간 48분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 150,
    "leaveGrantLabel": "2시간 30분"
  },
  {
    "employeeId": "CT21040030",
    "name": "김현주",
    "part": "FD 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT22040030",
    "name": "노지수",
    "part": "PLN 2",
    "div": "",
    "rank": "",
    "nightMinutes": 60,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 60,
    "holidayWorkMinutes": 60,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 120,
    "holidayGrantMinutes": 120,
    "leaveGrantMinutes": 120,
    "overtimeDayCount": 2,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "1시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 2,
    "roundedGrantMinutes": 120,
    "leaveGrantLabel": "2시간 0분"
  },
  {
    "employeeId": "CT25010020",
    "name": "노지수",
    "part": "CDA 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT19040040",
    "name": "류성렬",
    "part": "digital marketing 3",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 194,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 291,
    "overtimeDayCount": 1,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "3시간 14분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 270,
    "leaveGrantLabel": "4시간 30분"
  },
  {
    "employeeId": "CT21080030",
    "name": "박경우",
    "part": "CDC 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 232,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 348,
    "overtimeDayCount": 2,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "3시간 52분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 330,
    "leaveGrantLabel": "5시간 30분"
  },
  {
    "employeeId": "CT22020020",
    "name": "박나래",
    "part": "UXUI 1",
    "div": "",
    "rank": "",
    "nightMinutes": 91,
    "overtimeMinutes": 319,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 60,
    "holidayWorkMinutes": 60,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 120,
    "holidayGrantMinutes": 120,
    "leaveGrantMinutes": 614,
    "overtimeDayCount": 2,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "1시간 31분",
    "overtimeLabel": "5시간 19분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 2,
    "roundedGrantMinutes": 600,
    "leaveGrantLabel": "10시간 0분"
  },
  {
    "employeeId": "CT21050010",
    "name": "박민지",
    "part": "CDA 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT19010010",
    "name": "박성경",
    "part": "CDB 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 129,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 193.5,
    "overtimeDayCount": 1,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "2시간 9분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 180,
    "leaveGrantLabel": "3시간 0분"
  },
  {
    "employeeId": "CT23120010",
    "name": "박성경",
    "part": "CDC 2",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 77,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 115.5,
    "overtimeDayCount": 1,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "1시간 17분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 90,
    "leaveGrantLabel": "1시간 30분"
  },
  {
    "employeeId": "CT19040020",
    "name": "박소미",
    "part": "CDA 2",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT23120050",
    "name": "박소영",
    "part": "CDB 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT24010040",
    "name": "박소현",
    "part": "CDB 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 379,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 568.5,
    "overtimeDayCount": 3,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "6시간 19분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 540,
    "leaveGrantLabel": "9시간 0분"
  },
  {
    "employeeId": "CT19100010",
    "name": "박예림",
    "part": "UXUI 3",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT22050010",
    "name": "박은비",
    "part": "CDA 2",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 250,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 375,
    "overtimeDayCount": 2,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "4시간 10분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 360,
    "leaveGrantLabel": "6시간 0분"
  },
  {
    "employeeId": "CT24110010",
    "name": "박정현",
    "part": "UXUI 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT22040020",
    "name": "박지연",
    "part": "FD 4",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT24090070",
    "name": "박지연",
    "part": "CDA 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 45,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 67.5,
    "overtimeDayCount": 1,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 45분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 60,
    "leaveGrantLabel": "1시간 0분"
  },
  {
    "employeeId": "CT19040030",
    "name": "박진아",
    "part": "CDC 3",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 101,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 151.5,
    "overtimeDayCount": 5,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "1시간 41분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 150,
    "leaveGrantLabel": "2시간 30분"
  },
  {
    "employeeId": "CT26010020",
    "name": "박하늘",
    "part": "PLN 2",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT24050030",
    "name": "배민지",
    "part": "FD 4",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT24090020",
    "name": "배서은",
    "part": "CDA 2",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT25080010",
    "name": "백찬",
    "part": "Management Support",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 143,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 214.5,
    "overtimeDayCount": 1,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "2시간 23분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 210,
    "leaveGrantLabel": "3시간 30분"
  },
  {
    "employeeId": "CT24040030",
    "name": "송지원",
    "part": "Management Support",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 139,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 208.5,
    "overtimeDayCount": 1,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "2시간 19분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 180,
    "leaveGrantLabel": "3시간 0분"
  },
  {
    "employeeId": "CT25050020",
    "name": "송현지",
    "part": "CDC 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 75,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 112.5,
    "overtimeDayCount": 1,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "1시간 15분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 90,
    "leaveGrantLabel": "1시간 30분"
  },
  {
    "employeeId": "CT24110020",
    "name": "신민경",
    "part": "CDB 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT18120020",
    "name": "신일오",
    "part": "CDC",
    "div": "",
    "rank": "",
    "nightMinutes": 6,
    "overtimeMinutes": 1128,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 1695,
    "overtimeDayCount": 6,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 6분",
    "overtimeLabel": "18시간 48분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 1680,
    "leaveGrantLabel": "28시간 0분"
  },
  {
    "employeeId": "CT24050040",
    "name": "안주희",
    "part": "CDA 2",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT24040010",
    "name": "양희주",
    "part": "CDA 2",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 483,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 724.5,
    "overtimeDayCount": 4,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "8시간 3분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 720,
    "leaveGrantLabel": "12시간 0분"
  },
  {
    "employeeId": "CT16050010",
    "name": "어소영",
    "part": "UXUI",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 23,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 34.5,
    "overtimeDayCount": 1,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 23분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 30,
    "leaveGrantLabel": "0시간 30분"
  },
  {
    "employeeId": "CT22050020",
    "name": "오라영",
    "part": "FD 2",
    "div": "",
    "rank": "",
    "nightMinutes": 151,
    "overtimeMinutes": 1247,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 1946,
    "overtimeDayCount": 6,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "2시간 31분",
    "overtimeLabel": "20시간 47분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 1920,
    "leaveGrantLabel": "32시간 0분"
  },
  {
    "employeeId": "CT24120100",
    "name": "오해미",
    "part": "UXUI 2",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT25020030",
    "name": "윤성미",
    "part": "FD 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT25030040",
    "name": "윤예솜",
    "part": "digital marketing 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT25010040",
    "name": "윤은정",
    "part": "CDB 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 133,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 199.5,
    "overtimeDayCount": 1,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "2시간 13분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 180,
    "leaveGrantLabel": "3시간 0분"
  },
  {
    "employeeId": "CT25110010",
    "name": "윤은채",
    "part": "CDC 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 77,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 115.5,
    "overtimeDayCount": 1,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "1시간 17분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 90,
    "leaveGrantLabel": "1시간 30분"
  },
  {
    "employeeId": "CT22030040",
    "name": "윤이나",
    "part": "FD 3",
    "div": "",
    "rank": "",
    "nightMinutes": 234,
    "overtimeMinutes": 1769,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 2770.5,
    "overtimeDayCount": 7,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "3시간 54분",
    "overtimeLabel": "29시간 29분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 2760,
    "leaveGrantLabel": "46시간 0분"
  },
  {
    "employeeId": "CT25030020",
    "name": "윤채은",
    "part": "CDC 3",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT23080010",
    "name": "윤희승",
    "part": "FD 2",
    "div": "",
    "rank": "",
    "nightMinutes": 188,
    "overtimeMinutes": 1413,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 2213.5,
    "overtimeDayCount": 6,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "3시간 8분",
    "overtimeLabel": "23시간 33분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 2190,
    "leaveGrantLabel": "36시간 30분"
  },
  {
    "employeeId": "CT22100010",
    "name": "이강해",
    "part": "PLN 2",
    "div": "",
    "rank": "",
    "nightMinutes": 60,
    "overtimeMinutes": 61,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 60,
    "holidayWorkMinutes": 60,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 120,
    "holidayGrantMinutes": 120,
    "leaveGrantMinutes": 211.5,
    "overtimeDayCount": 3,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "1시간 0분",
    "overtimeLabel": "1시간 1분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 2,
    "roundedGrantMinutes": 210,
    "leaveGrantLabel": "3시간 30분"
  },
  {
    "employeeId": "CT24120050",
    "name": "이대희",
    "part": "PLN 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 412,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 618,
    "overtimeDayCount": 5,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "6시간 52분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 600,
    "leaveGrantLabel": "10시간 0분"
  },
  {
    "employeeId": "CT18100020",
    "name": "이보은",
    "part": "digital marketing 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 1,
    "issueDates": [
      "2026-03-20"
    ],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT23100010",
    "name": "이서영",
    "part": "UXUI 2",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT26020040",
    "name": "이소곤",
    "part": "CDA 3",
    "div": "",
    "rank": "",
    "nightMinutes": 53,
    "overtimeMinutes": 838,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 1283.5,
    "overtimeDayCount": 4,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 53분",
    "overtimeLabel": "13시간 58분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 1260,
    "leaveGrantLabel": "21시간 0분"
  },
  {
    "employeeId": "CT25030060",
    "name": "이소연",
    "part": "UXUI 2",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 224,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 336,
    "overtimeDayCount": 2,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "3시간 44분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 330,
    "leaveGrantLabel": "5시간 30분"
  },
  {
    "employeeId": "CT19060010",
    "name": "이수근",
    "part": "digital marketing 2",
    "div": "",
    "rank": "",
    "nightMinutes": 37,
    "overtimeMinutes": 263,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 413,
    "overtimeDayCount": 0,
    "issueCount": 2,
    "issueDates": [
      "2026-03-10",
      "2026-03-13"
    ],
    "nightLabel": "0시간 37분",
    "overtimeLabel": "4시간 23분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 390,
    "leaveGrantLabel": "6시간 30분"
  },
  {
    "employeeId": "CT20020010",
    "name": "이수빈",
    "part": "UXUI 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 418,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 627,
    "overtimeDayCount": 3,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "6시간 58분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 600,
    "leaveGrantLabel": "10시간 0분"
  },
  {
    "employeeId": "CT21050040",
    "name": "이수빈",
    "part": "CDA 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 137,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 205.5,
    "overtimeDayCount": 1,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "2시간 17분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 180,
    "leaveGrantLabel": "3시간 0분"
  },
  {
    "employeeId": "CT19020020",
    "name": "이수윤",
    "part": "CDA 3",
    "div": "",
    "rank": "",
    "nightMinutes": 121,
    "overtimeMinutes": 2031,
    "holidayOvertimeMinutes": 485,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 485,
    "holidayOvertimeGrantMinutes": 730,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 730,
    "leaveGrantMinutes": 3837,
    "overtimeDayCount": 10,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "2시간 1분",
    "overtimeLabel": "33시간 51분",
    "holidayOvertimeConvertedHours": 12.167,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 3810,
    "leaveGrantLabel": "63시간 30분"
  },
  {
    "employeeId": "CT26020050",
    "name": "이수정",
    "part": "CDA 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT23070030",
    "name": "이유나",
    "part": "UXUI 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT25020020",
    "name": "이정민",
    "part": "UXUI 2",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 98,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 147,
    "overtimeDayCount": 1,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "1시간 38분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 120,
    "leaveGrantLabel": "2시간 0분"
  },
  {
    "employeeId": "CT20090010",
    "name": "이지연",
    "part": "CDB",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT18120010",
    "name": "이찬웅",
    "part": "UXUI 2",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 331,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 496.5,
    "overtimeDayCount": 3,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "5시간 31분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 480,
    "leaveGrantLabel": "8시간 0분"
  },
  {
    "employeeId": "CT16060010",
    "name": "이하원",
    "part": "UXUI 3",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT24120010",
    "name": "이해현",
    "part": "FD 3",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 298,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 447,
    "overtimeDayCount": 2,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "4시간 58분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 420,
    "leaveGrantLabel": "7시간 0분"
  },
  {
    "employeeId": "CT13050010",
    "name": "이현수",
    "part": "FD 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT19120010",
    "name": "이현지",
    "part": "UXUI 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 183,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 274.5,
    "overtimeDayCount": 1,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "3시간 3분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 270,
    "leaveGrantLabel": "4시간 30분"
  },
  {
    "employeeId": "CT23110020",
    "name": "이혜인",
    "part": "CDC 3",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 92,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 138,
    "overtimeDayCount": 1,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "1시간 32분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 120,
    "leaveGrantLabel": "2시간 0분"
  },
  {
    "employeeId": "CT25070010",
    "name": "임민하",
    "part": "CDA 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 83,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 124.5,
    "overtimeDayCount": 1,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "1시간 23분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 120,
    "leaveGrantLabel": "2시간 0분"
  },
  {
    "employeeId": "CT25050010",
    "name": "임승미",
    "part": "CDB 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 136,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 204,
    "overtimeDayCount": 1,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "2시간 16분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 180,
    "leaveGrantLabel": "3시간 0분"
  },
  {
    "employeeId": "CT24120060",
    "name": "임예지",
    "part": "PLN 2",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT26030010",
    "name": "임희정",
    "part": "CDA 3",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT19100030",
    "name": "장가람",
    "part": "CDA 3",
    "div": "",
    "rank": "",
    "nightMinutes": 131,
    "overtimeMinutes": 1963,
    "holidayOvertimeMinutes": 240,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 240,
    "holidayOvertimeGrantMinutes": 360,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 360,
    "leaveGrantMinutes": 3370,
    "overtimeDayCount": 10,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "2시간 11분",
    "overtimeLabel": "32시간 43분",
    "holidayOvertimeConvertedHours": 6,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 3360,
    "leaveGrantLabel": "56시간 0분"
  },
  {
    "employeeId": "CT23070040",
    "name": "장민경",
    "part": "PLN 2",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT25030010",
    "name": "장하림",
    "part": "UXUI 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT22040010",
    "name": "장한가람",
    "part": "UXUI 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 430,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 645,
    "overtimeDayCount": 4,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "7시간 10분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 630,
    "leaveGrantLabel": "10시간 30분"
  },
  {
    "employeeId": "CT25030050",
    "name": "장현수",
    "part": "UXUI 3",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT23110040",
    "name": "장혜민",
    "part": "CDA 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT25070030",
    "name": "정다혜",
    "part": "UXUI 3",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT24050050",
    "name": "정서영",
    "part": "CDA 2",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 294,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 441,
    "overtimeDayCount": 3,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "4시간 54분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 420,
    "leaveGrantLabel": "7시간 0분"
  },
  {
    "employeeId": "CT15100010",
    "name": "정주리",
    "part": "CDA 2",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 213,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 319.5,
    "overtimeDayCount": 4,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "3시간 33분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 300,
    "leaveGrantLabel": "5시간 0분"
  },
  {
    "employeeId": "CT14040020",
    "name": "정주희",
    "part": "UXUI 2",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 147,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 220.5,
    "overtimeDayCount": 2,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "2시간 27분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 210,
    "leaveGrantLabel": "3시간 30분"
  },
  {
    "employeeId": "CT26030020",
    "name": "정지영",
    "part": "digital marketing design",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT24120080",
    "name": "정지은",
    "part": "UXUI 2",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 62,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 93,
    "overtimeDayCount": 1,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "1시간 2분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 90,
    "leaveGrantLabel": "1시간 30분"
  },
  {
    "employeeId": "CT25060030",
    "name": "정지혜",
    "part": "CDC 2",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT24120030",
    "name": "정현지",
    "part": "CDC 3",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 135,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 202.5,
    "overtimeDayCount": 2,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "2시간 15분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 180,
    "leaveGrantLabel": "3시간 0분"
  },
  {
    "employeeId": "CT26020020",
    "name": "조명정",
    "part": "PLN 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 67,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 100.5,
    "overtimeDayCount": 1,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "1시간 7분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 90,
    "leaveGrantLabel": "1시간 30분"
  },
  {
    "employeeId": "CT14010010",
    "name": "조병준",
    "part": "FD 4",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT24080020",
    "name": "조재윤",
    "part": "UXUI 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT22060030",
    "name": "조지수",
    "part": "CDA 2",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 59,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 88.5,
    "overtimeDayCount": 1,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 59분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 60,
    "leaveGrantLabel": "1시간 0분"
  },
  {
    "employeeId": "CT24120070",
    "name": "조진서",
    "part": "UXUI 2",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 141,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 211.5,
    "overtimeDayCount": 1,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "2시간 21분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 210,
    "leaveGrantLabel": "3시간 30분"
  },
  {
    "employeeId": "CT22110030",
    "name": "조진아",
    "part": "CDA 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT24090060",
    "name": "조하은",
    "part": "CDB 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT25110020",
    "name": "주성훈",
    "part": "FD 4",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT15100020",
    "name": "진보라",
    "part": "CDA 3",
    "div": "",
    "rank": "",
    "nightMinutes": 28,
    "overtimeMinutes": 1831,
    "holidayOvertimeMinutes": 591,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 591,
    "holidayOvertimeGrantMinutes": 942,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 942,
    "leaveGrantMinutes": 3702.5,
    "overtimeDayCount": 9,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 28분",
    "overtimeLabel": "30시간 31분",
    "holidayOvertimeConvertedHours": 15.7,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 3690,
    "leaveGrantLabel": "61시간 30분"
  },
  {
    "employeeId": "CT24060010",
    "name": "차채란",
    "part": "CDA 2",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 199,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 298.5,
    "overtimeDayCount": 1,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "3시간 19분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 270,
    "leaveGrantLabel": "4시간 30분"
  },
  {
    "employeeId": "CT16050030",
    "name": "차혜린",
    "part": "CDA 2",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 352,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 528,
    "overtimeDayCount": 4,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "5시간 52분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 510,
    "leaveGrantLabel": "8시간 30분"
  },
  {
    "employeeId": "CT13040010",
    "name": "최병남",
    "part": "FD 1",
    "div": "",
    "rank": "",
    "nightMinutes": 61,
    "overtimeMinutes": 334,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 531.5,
    "overtimeDayCount": 2,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "1시간 1분",
    "overtimeLabel": "5시간 34분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 510,
    "leaveGrantLabel": "8시간 30분"
  },
  {
    "employeeId": "CT22070040",
    "name": "최수빈",
    "part": "UXUI 1",
    "div": "",
    "rank": "",
    "nightMinutes": 60,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 60,
    "holidayWorkMinutes": 60,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 120,
    "holidayGrantMinutes": 120,
    "leaveGrantMinutes": 120,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "1시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 2,
    "roundedGrantMinutes": 120,
    "leaveGrantLabel": "2시간 0분"
  },
  {
    "employeeId": "CT24110050",
    "name": "최시영",
    "part": "FD 3",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 529,
    "holidayOvertimeMinutes": 1443,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 1443,
    "holidayOvertimeGrantMinutes": 2166,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 2166,
    "leaveGrantMinutes": 2959.5,
    "overtimeDayCount": 6,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "8시간 49분",
    "holidayOvertimeConvertedHours": 36.1,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 2940,
    "leaveGrantLabel": "49시간 0분"
  },
  {
    "employeeId": "CT12050010",
    "name": "최은애",
    "part": "FD 3",
    "div": "",
    "rank": "",
    "nightMinutes": 158,
    "overtimeMinutes": 1780,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 2749,
    "overtimeDayCount": 7,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "2시간 38분",
    "overtimeLabel": "29시간 40분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 2730,
    "leaveGrantLabel": "45시간 30분"
  },
  {
    "employeeId": "CT23080020",
    "name": "최하영",
    "part": "FD 3",
    "div": "",
    "rank": "",
    "nightMinutes": 27,
    "overtimeMinutes": 481,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 735,
    "overtimeDayCount": 2,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 27분",
    "overtimeLabel": "8시간 1분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 720,
    "leaveGrantLabel": "12시간 0분"
  },
  {
    "employeeId": "CT21080040",
    "name": "탁경아",
    "part": "UXUI 3",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT23040010",
    "name": "한세희",
    "part": "UXUI 2",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 237,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 355.5,
    "overtimeDayCount": 2,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "3시간 57분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 330,
    "leaveGrantLabel": "5시간 30분"
  },
  {
    "employeeId": "CT22070030",
    "name": "한혜진",
    "part": "digital marketing 2",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 20,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 30,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 20분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 30,
    "leaveGrantLabel": "0시간 30분"
  },
  {
    "employeeId": "CT22050050",
    "name": "홍민정",
    "part": "CDA 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT24100020",
    "name": "황라현",
    "part": "UXUI 1",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 0,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 0,
    "overtimeDayCount": 0,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "0시간 0분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 0,
    "leaveGrantLabel": "0시간 0분"
  },
  {
    "employeeId": "CT21030020",
    "name": "황인영",
    "part": "UXUI 2",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 109,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 163.5,
    "overtimeDayCount": 1,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "1시간 49분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 150,
    "leaveGrantLabel": "2시간 30분"
  },
  {
    "employeeId": "CT25020010",
    "name": "황지현",
    "part": "UXUI 2",
    "div": "",
    "rank": "",
    "nightMinutes": 0,
    "overtimeMinutes": 394,
    "holidayOvertimeMinutes": 0,
    "holidayNightMinutes": 0,
    "holidayWorkMinutes": 0,
    "holidayOvertimeGrantMinutes": 0,
    "holidayNightGrantMinutes": 0,
    "holidayGrantMinutes": 0,
    "leaveGrantMinutes": 591,
    "overtimeDayCount": 3,
    "issueCount": 0,
    "issueDates": [],
    "nightLabel": "0시간 0분",
    "overtimeLabel": "6시간 34분",
    "holidayOvertimeConvertedHours": 0,
    "holidayNightConvertedHours": 0,
    "roundedGrantMinutes": 570,
    "leaveGrantLabel": "9시간 30분"
  }
];
